import './global.css';

export const metadata = {
  title: 'Welcome to clay-design-system',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-full bg-white">
      <body className="h-full">{children}</body>
    </html>
  );
}
